import streamlit as st
import pandas as pd
import altair as alt
from vis_agent import VisAgent
from common import lookup_dataset_by_name, render_aggrid

st.title("Data Analysts Salary explorer")
st.markdown("Ask a question about data analyst salaries to generate a custom chart.")
st.markdown("Tip: For best results, write prompts that clearly describe how you want to visualize Data Analyst salary trends, such as changes over time or comparisons grouped by categories like state or seniority. Example prompts include “How have Data Analyst salaries changed over time?” and “Visualize median Data Analyst salary by state.” When asking about total cost, keep the prompt simple such as “How does total cost change by state?” and avoid adding calculations like median, since the system may not correctly recognize the columns across datasets. Also note that skillset visualizations may not display individual skills clearly because skillsets are stored as arrays and are not always separated into individual skill values in the chart. If a query does not work, try simplifying the prompt or focusing on salary trends grouped by variables like state, seniority, or time.")
user_prompt = st.chat_input("What would you like to visualize?")

if user_prompt:
    va = VisAgent()
    chart_result = va.run(user_prompt)

    print('chart_result:', chart_result)

    st.markdown(f'#### **Prompt:** "{user_prompt}"')

    st.space()

    if chart_result['status'] == 'success':

        st.altair_chart(chart_result['chart_obj'])
        st.space()

        st.markdown(chart_result['desc'])
        st.space()
        st.markdown('**Code behind this chart**')
        st.code(chart_result['code'], language="python")

        st.space()

        st.markdown("**Data behind this chart**")
        render_aggrid(lookup_dataset_by_name(chart_result['dataset']))


        caption_text = f"""**Note on generation:** This visualization, description, and 
        code were generated by AI, Gemini 2.5 Flash and Gemini 2.5 Flash Lite. 
        The agent independently chose the dataset and produced the chart based on the user's prompt.
        """
        st.markdown(caption_text)

    else:
        st.error(chart_result['message'])
